name: flutter_quill
description: A rich text editor supporting mobile and web (Demo App @ bulletjournal.us)
version: 5.4.1
homepage: 'https://bulletjournal.us/home/index.html'
repository: 'https://github.com/singerdmx/flutter-quill'
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.2.0
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  quiver: ^3.1.0
  string_validator: ^0.3.0
  tuple: ^2.0.0
  url_launcher: ^6.1.2
  pedantic: ^1.11.1
  video_player: ^2.4.2
  characters: ^1.2.0
  diff_match_patch: ^0.4.1
  i18n_extension: ^5.0.0
  gallery_saver: ^2.3.2
  device_info_plus: ^4.0.0
  platform: ^3.1.0
  math_keyboard: ^0.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: null
